### ISSUE TITLE
failed to validate auth token. issue a new one

### ISSUE THREAD

**Issue by BigWebstas** [itsankoff/gopro-plus#6] opened 2024-10-10 19:01 UTC
It keeps throwing this error in the log, i have redone the token several times on different computers with the same result

**Comment by BigWebstas** [comment] 2024-10-10 20:45
I can get the token from Dev>Application>Cookies>gp_access_token
![image](https://github.com/user-attachments/assets/fc239fad-5425-432f-8ade-cb695021e888)

**Comment by adam-kozlowski-280** [comment] 2024-10-15 09:12
@BigWebstas I have the same issue and started digging. When I've checked status code in `.validate()` step it was 404 but it is propably due to url mismatch (now url looks like `https://gopro.com/media-library/` but this class tries to get media from `https://api.gopro.com/media/search`). When I've updated the url to `media-library`, then I've got 403 instead, which indicates wrong `api_token` :/ 
@itsankoff do you have any suggestion how to overcome this issue?

**Comment by PiotrKrzyzek** [comment] 2024-10-18 16:34
Indeed. I receive the same issue.

**Comment by rfsbraz** [comment] 2024-11-23 14:30
same

**Comment by micah** [comment] 2024-11-23 16:29
same

**Comment by szaracz** [comment] 2024-12-06 21:44
+1 to the thread above.

**Comment by itsankoff** [comment] 2024-12-26 12:26
@BigWebstas @adam-kozlowski-280 @PiotrKrzyzek @Louiscars190 @rfsbraz @szaracz:

Folks the issue is fixed. The problem was that GoPro cloud changed their authentication mechanism from pure JWT to more sophisticated JWE which encrypts the content of the JWT token (kindof).

So the new version 1.4.3 is tested but keep in mind that now you need to provide additional parameter which is `USER_ID`.

Closing the issue for now. If you experience any other issues, let me know, or feel free to contribute to the project

**Closed by itsankoff** 2024-12-26 12:26 UTC
